/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_ECM_ecm_params */

#ifndef _Included_org_gmplib_gmpjni_ECM_ecm_params
#define _Included_org_gmplib_gmpjni_ECM_ecm_params
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gmplib_gmpjni_ECM_ecm_params_MOD_NOBASE2
#define org_gmplib_gmpjni_ECM_ecm_params_MOD_NOBASE2 -1L
#undef org_gmplib_gmpjni_ECM_ecm_params_MOD_DEFAULT
#define org_gmplib_gmpjni_ECM_ecm_params_MOD_DEFAULT 0L
#undef org_gmplib_gmpjni_ECM_ecm_params_MOD_MPZ
#define org_gmplib_gmpjni_ECM_ecm_params_MOD_MPZ 1L
#undef org_gmplib_gmpjni_ECM_ecm_params_MOD_BASE2
#define org_gmplib_gmpjni_ECM_ecm_params_MOD_BASE2 2L
#undef org_gmplib_gmpjni_ECM_ecm_params_MOD_MODMULN
#define org_gmplib_gmpjni_ECM_ecm_params_MOD_MODMULN 3L
#undef org_gmplib_gmpjni_ECM_ecm_params_MOD_REDC
#define org_gmplib_gmpjni_ECM_ecm_params_MOD_REDC 4L
#undef org_gmplib_gmpjni_ECM_ecm_params_ECM
#define org_gmplib_gmpjni_ECM_ecm_params_ECM 0L
#undef org_gmplib_gmpjni_ECM_ecm_params_PM1
#define org_gmplib_gmpjni_ECM_ecm_params_PM1 1L
#undef org_gmplib_gmpjni_ECM_ecm_params_PP1
#define org_gmplib_gmpjni_ECM_ecm_params_PP1 2L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_DEFAULT
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_DEFAULT -1L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_SUYAMA
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_SUYAMA 0L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_BATCH_SQUARE
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_BATCH_SQUARE 1L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_BATCH_2
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_BATCH_2 2L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_BATCH_32BITS_D
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_BATCH_32BITS_D 3L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_WEIERSTRASS
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_WEIERSTRASS 5L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_HESSIAN
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_HESSIAN 6L
#undef org_gmplib_gmpjni_ECM_ecm_params_PARAM_TORSION
#define org_gmplib_gmpjni_ECM_ecm_params_PARAM_TORSION 7L
#undef org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_MONTGOMERY
#define org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_MONTGOMERY 1L
#undef org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_WEIERSTRASS
#define org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_WEIERSTRASS 2L
#undef org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_HESSIAN
#define org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_HESSIAN 3L
#undef org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_WEIERSTRASS_COMPLETE
#define org_gmplib_gmpjni_ECM_ecm_params_EC_TYPE_WEIERSTRASS_COMPLETE 4L
#undef org_gmplib_gmpjni_ECM_ecm_params_LAW_AFFINE
#define org_gmplib_gmpjni_ECM_ecm_params_LAW_AFFINE 1L
#undef org_gmplib_gmpjni_ECM_ecm_params_LAW_HOMOGENEOUS
#define org_gmplib_gmpjni_ECM_ecm_params_LAW_HOMOGENEOUS 2L
/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_method
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1method
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_x
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1x
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_y
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1y
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_rng_seed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1rng_1seed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_param
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1param
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_sigma
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1sigma
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_sigma_is_A
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1sigma_1is_1A
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_go
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1go
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_B1done
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1B1done
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_B2min
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1B2min
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_B2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1B2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_k
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1k
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_S
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1S
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_repr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1repr
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_nobase2step2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1nobase2step2
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_verbose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1verbose
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_chkfilename
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1chkfilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_treefilename
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1treefilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_maxmem
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1maxmem
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_stage1time
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1stage1time
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_use_ntt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1use_1ntt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_stop_callback
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1stop_1callback
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_batch_s
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1batch_1s
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_batch_last_B1_used
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1batch_1last_1B1_1used
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gpu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gpu
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gpu_device
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gpu_1device
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gpu_device_init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gpu_1device_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gpu_number_of_curves
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gpu_1number_1of_1curves
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gw_k
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gw_1k
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gw_b
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gw_1b
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gw_n
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gw_1n
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_gw_c
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1gw_1c
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_type
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1type
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_law
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1law
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_disc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1disc
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_a1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1a1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_a2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1a2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_a3
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1a3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_a4
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1a4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_a6
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1a6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_buf
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1buf
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    native_set_E_sq
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_native_1set_1E_1sq
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_init
  (JNIEnv *, jobject);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_fini
  (JNIEnv *, jobject);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    openStream
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_openStream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    closeStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_closeStream
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    set_errstreamh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_set_1errstreamh
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    set_outstreamh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_set_1outstreamh
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_ECM_ecm_params
 * Method:    release
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECM_00024ecm_1params_release
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
