/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_ECM_ecm_stop_callback */

#ifndef _Included_org_gmplib_gmpjni_ECM_ecm_stop_callback
#define _Included_org_gmplib_gmpjni_ECM_ecm_stop_callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
